server:
  port: 9000

spring:
  application:
    name: redis_distributed_lock
  redis:
    host: 192.168.1.104
    password: myredis
    jedis:
      pool:
        max-active: 20
        max-wait: 10000
        max-idle: 10
        min-idle: 5
        timeout: 100000
    database: 3
    #timeout: 100000   #连接超时时间
#    lettuce:
#      pool:
#        max-active: 20  #；连接池最大连接数
#        max-idle: 10    #最大空闲连接
#        min-idle: 5     #最小空闲连接
#        max-wait: 10000  #连接池最大阻塞等待时间
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/db1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.distributed.lock.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.founder: debug
    org.springframework: warn
